sudo: required

language: python

services:
  - docker

before_install:
  - mkdir test_folder

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - cd test_folder
  - git clone -b $BRANCH https://github.com/qiaseq/read-trimmer.git
  - cd read-trimmer
  - sudo docker build -t qiaseq/read-trimmer --build-arg branch=$BRANCH .
  - sudo docker run --entrypoint python qiaseq/read-trimmer /read-trimmer/tests/test_qiaseq_trim.py -v
  - sudo docker run qiaseq/read-trimmer --r1 /read-trimmer/tests/test_data/test_dna_R1.fastq.gz --r2 /read-trimmer/tests/test_data/test_dna_R2.fastq.gz --out-r1 temp.R1.fastq --out-r2 temp.R2.fastq --out-metrics temp.metrics.txt --seqtype dna --primer-file /read-trimmer/tests/test_data/test_dna_primers_2.txt --primer-col 3 --umi-len 12 --common-seq-len 8
  - sudo docker run qiaseq/read-trimmer --r1 /read-trimmer/tests/test_data/test_duplex_R1.fastq.gz --r2 /read-trimmer/tests/test_data/test_duplex_R2.fastq.gz --out-r1 temp.R1.fastq --out-r2 temp.R2.fastq --out-metrics temp.metrics.txt --seqtype dna --primer-file /read-trimmer/tests/test_data/test_duplex_primers.txt --primer-col 3 --umi-len 12 --common-seq-len 8 --is-duplex --is-phased-adapters --is-nextseq

