sudo: required

language: python

services:
  - docker

before_install:
  - mkdir test_folder

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - git clone https://github.com/qiaseq/read-trimmer.git
  - cd read-trimmer
  - sudo docker build -t qiaseq/read-trimmer .
  - sudo docker run --entrypoint python qiaseq/read-trimmer /read-trimmer/tests/test_qiaseq_trim.py -v
